name: Plotty
version: 2.1
main: com.daviga404.Plotty
softdepend: [WorldEdit, WorldGuard]
commands:
    plot:
        description: Main Plotty command.
        usage: /plot ?
    plotty:
        description: Main Plotty command.
        usage: /plot ?