name: Plotty
version: ${pluginversion}
main: com.daviga404.Plotty
api-version: 1.20
authors: [Daviga404, The Worldwide Minecraft Alliance]
softdepend: [WorldEdit, WorldGuard]

commands:
    plot:
        description: Main Plotty command.
        usage: /plot ?
    plotty:
        description: Main Plotty command.
        usage: /plot ?